### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by UltraCakeBakery**
SvelteKit has not introduced any breaking changes. Only bug fixes and security patches.
Svelte 4.0 only added features we don't use and optimized some API documentation in the auto complete.
ESlint is now the official plugin.
Vitest has been updated to 1.0 (which is the same as the beta release, but now just a different version number)
Other dependencies are related to these and just have been updated to their latest version.

### CODE REVIEW

**Comment by UltraCakeBakery** [comment]
Not sure why the commit is named 'init flipclock' lol

**Comment by UltraCakeBakery** [comment]
I also moved all the dependencies to devDependencies (where they belong)

**Comment by justingolden21** [comment]
Thanks for this change! Looks good in testing. Gonna merge

**Comment by justingolden21** [comment]
Merging into dev rn

**Comment by justingolden21** [comment]
Looks good in dev, merging to master

**Pull request merged**
